import Link from 'next/link';
import { BRAND } from '@/lib/brand';

const walkthrough = [
  {number:'02',title:'CV parsing and candidate profiles',href:'/hr/cv-parsing',action:'Open CV parsing',body:'Upload a text-based PDF or DOCX, inspect the extracted fields, correct missing information, then save the profile. The saved profile contains skills, experience, education and the source CV. Parsing completeness is a review aid, not a measured accuracy guarantee.'},
  {number:'03',title:'Smart candidate matching',href:'/hr/ai-matching',action:'Open candidate matching',body:'Select a job and compare indexed candidates. The fit indicator uses semantic similarity (55%), required-skill coverage (30%) and the experience requirement (15%). Scores range from 0 to 100; duplicate skills count once. Where no skills are specified, their weight is redistributed.'},
  {number:'04',title:'Application scoring and recommendations',href:'/hr/candidates',action:'Open candidate evaluations',body:'Open a candidate’s application and evaluate job fit. The evidence score combines job match (40%), completed exams (30%) and completed interviews (30%). Missing evidence is shown as pending, with available weights rescaled. HR reviews the evidence and makes the decision.'},
  {number:'05',title:'Assessment exams',href:'/hr/assessments',action:'Open assessments',body:'Create an exam with multiple-choice or written questions, points and a grading rubric. Assign it to an application. The candidate starts a timed attempt and submits answers. Multiple-choice answers are graded against the key; written answers are evaluated against the rubric. Completed results cannot be changed by resubmission.'},
  {number:'06',title:'AI interviewer',href:'/hr/ai-interview',action:'Open interviews',body:'Start an interview linked to the candidate’s application. The interviewer asks follow-up questions and stores the transcript. After at least three substantive answers, end the interview to produce a validated evaluation. Browser speech input and read-aloud are optional; text remains available.'},
];
export default function PresentationPage(){return <div className="max-w-5xl mx-auto space-y-6 pb-8">
  <header className="glass-card p-7"><p className="text-xs uppercase tracking-widest text-primary">{BRAND.name} · Recruitment operations</p><h1 className="text-3xl font-semibold mt-3">Application walkthrough</h1><p className="text-muted-foreground mt-3">Follow a candidate from their CV through evaluation, with a clear explanation of the evidence behind each result.</p></header>
  <section className="glass-card p-6"><p className="text-xs text-primary">01 · Vendor background</p><h2 className="text-xl font-semibold mt-2">Obrix Labs</h2><p className="mt-3 text-lg">15 years of experience</p><p className="text-sm text-muted-foreground mt-3">HireOps brings together recruitment workflows, document extraction, semantic matching, structured assessments and AI-assisted interviews. Its implementation uses Next.js, TypeScript, PostgreSQL, Supabase authentication and storage, and configurable AI inference providers.</p></section>
  {walkthrough.map(item=><section key={item.number} className="glass-card p-6"><p className="text-xs text-primary">{item.number} · Recruitment workflow</p><h2 className="text-xl font-semibold mt-2">{item.title}</h2><p className="text-sm text-muted-foreground mt-3 leading-7">{item.body}</p><Link href={item.href} className="inline-block mt-4 rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">{item.action} →</Link></section>)}
  <section className="glass-card p-6 space-y-4"><p className="text-xs text-primary">07 · Integration, security and Q&amp;A</p><h2 className="text-xl font-semibold">Questions to address during the walkthrough</h2>
    <details className="border-b border-white/10 pb-3"><summary className="cursor-pointer font-medium">Where are data and files stored?</summary><p className="text-sm text-muted-foreground mt-2">Recruitment records are stored in Supabase PostgreSQL and uploaded documents in private storage buckets. Hosting is configured for AWS Amplify. Confirm the deployed regions, retention rules and contractual requirements with the organization before a production rollout.</p></details>
    <details className="border-b border-white/10 pb-3"><summary className="cursor-pointer font-medium">How is candidate information isolated?</summary><p className="text-sm text-muted-foreground mt-2">Authenticated API checks and database row-level policies enforce organization and candidate ownership. Candidates cannot access another candidate’s exams, interviews or profiles. Answer keys and grading writes are handled on the server. Suspended users cannot call protected APIs.</p></details>
    <details className="border-b border-white/10 pb-3"><summary className="cursor-pointer font-medium">Which AI integrations are available?</summary><p className="text-sm text-muted-foreground mt-2">The implementation supports OpenRouter, Groq, Together, Fireworks and DeepInfra. Administrators configure chat inference and encrypted credentials. Embeddings use the deployment’s configured provider and fixed model. Resume text and interview answers are sent to the configured AI provider when those features run.</p></details>
    <details className="border-b border-white/10 pb-3"><summary className="cursor-pointer font-medium">Does a match score guarantee suitability?</summary><p className="text-sm text-muted-foreground mt-2">No. It measures evidence against the job criteria, not the probability of a successful hire. AI interpretation can be wrong. Review the source CV, skills, exam results and interview transcript before deciding. Human reviewers retain hiring authority.</p></details>
    <details><summary className="cursor-pointer font-medium">Are government SSO, HRIS and external calendars connected?</summary><p className="text-sm text-muted-foreground mt-2">They are not preconfigured integrations in this deployment. Email/password authentication, Supabase services and configured AI inference are implemented. External identity, HRIS and calendar connectors need the organization’s endpoints and credentials plus separate acceptance testing.</p></details>
  </section>
</div>;}
