import assert from 'node:assert/strict';
import { calculateMatch, skillOverlap, combineEvidence, percent } from '../src/lib/scoring';
import { assessmentSchema } from '../src/lib/assessment-schema';
assert.deepEqual(skillOverlap(['JavaScript','JS','React','React.js'],['javascript','JavaScript','React']),{matchedSkills:['JavaScript','React'],missingSkills:[]});
assert.deepEqual(skillOverlap(['JavaScript','C++'],['Java','C']),{matchedSkills:[],missingSkills:['Java','C']});
assert.equal(calculateMatch(100,['JS'],['JavaScript'],0,5).experience,0);
assert.equal(calculateMatch(100,['JS'],['JavaScript'],5,5).overall,100);
assert.equal(calculateMatch(100,[],[],0,0).overall,100);
assert.equal(percent(NaN),0);
assert.equal(percent(110),100);
assert.equal(percent(-10),0);
assert.equal(combineEvidence(null,null,null).overall,null);
assert.equal(combineEvidence(80,null,null).overall,80);
assert.equal(combineEvidence(80,null,null).complete,false);
assert.equal(combineEvidence(80,100,60).overall,80);
assert.equal(combineEvidence(0,0,0).overall,0);
assert.equal(assessmentSchema.safeParse({title:'Exam',questions:[]}).success,false);
assert.equal(assessmentSchema.safeParse({title:'Exam',questions:[{prompt:'Select one',questionType:'multiple_choice',options:['A','B'],correctAnswer:'C'}]}).success,false);
assert.equal(assessmentSchema.safeParse({title:'Exam',durationMinutes:0,questions:[{prompt:'Select one',questionType:'multiple_choice',options:['A','B'],correctAnswer:'A'}]}).success,false);
assert.equal(assessmentSchema.safeParse({title:'Exam',questions:[{prompt:'Select one',questionType:'multiple_choice',options:['A','B'],correctAnswer:'A'}]}).success,true);
console.log('PASS: 17 scoring and exam-validation assertions');
